version: "3.6"
services:
  lyncex:
    image: lyncex:latest
    ports:
    - 11011:11011
  nginx:
    image: nginx:1.17.2
    ports:
    - 1144:1144
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  setup:
    build: .
    volumes:
    - ./:/root
    depends_on:
    - lyncex